services:
    symfony_app:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID}
        ports:
            - "8410:8410"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
